package br.com.getnet.posdigital.mifare

enum class MifareMethod {

    SEARCH_CARD, SEARCH_CARD_AND_ACTIVATE, AUTH_SECTOR_KEY_A, AUTH_SECTOR_KEY_B,
    AUTH_BLOCK_KEY_A, AUTH_BLOCK_KEY_B, ACTIVATE, HALT, SERIAL_NO, CLOSE, DECREMENT,
    INCREMENT, EXIST, READ, WRITE, RESTORE, TRANSFER

}